version: '3.8'

services:
  mysqld-exporter:
    image: prom/mysqld-exporter
    container_name: mysqld_exporter
    ports:
      - 9104:9104
    volumes:
      #- ./my.cnf:/.my.cnf
      #- ./mysqld_exporter.yml:/etc/mysqld_exporter/mysqld_exporter.yml
      - ./my.cnf:/etc/mysqld_exporter/my.cnf
    command:
      #- --config.my-cnf=/etc/mysqld_exporter/mysqld_exporter.yml
      - --config.my-cnf=/etc/mysqld_exporter/my.cnf
    restart: unless-stopped
    networks:
        - apisix-network
networks:
  apisix-network:
    external: true
    name: docker-apisix_apisix  # 假设 docker-apisix_apisix 所在的网络名为 docker-apisix_default
  